# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: npmAuthenticate@0
  inputs:
    workingFile: '.npmrc'

# - task: Npm@1
#   inputs:
#     command: 'install'
#     workingDir: 'webapp'
#     verbose: true
#     customRegistry: 'useFeed'
#     customFeed: 'e7adb198-e342-472e-9697-058f7e39bfa6'

- script: cd webapp && npm install && npm run test
  displayName: 'Running tests'



- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'sonarqube-vm'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'kona-lms_lms-public-e22-pipelines_AYfg_oSkdXc6EdxKKNwZ'
    cliSources: '.'

- task: SonarQubeAnalyze@5

- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'